name: Quasar CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Global Dependencies
        run: |
          npm install -g @quasar/cli

      - name: Install Project Dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          quasar build
        env:
          CI: true

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            dist
            .quasar
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  deploy:
    needs: build
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore cached build
        uses: actions/cache@v3
        with:
          path: |
            dist
            .quasar
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: 'dist/spa/*'
          target: '/var/www/frontend_case_management'
